---

- hosts: ansible
  gather_facts: False
  remote_user: root
  become: yes
  become_method: sudo
  
  tasks:
    - name: 创建/opt/data目录
      file:      
        dest=/opt/data/{{item}}
        state=directory
        mode=0644
      with_items:
      - cfssl
      - flannel

    - name: 下载{{CFSSL_URL}}
      get_url:
        url={{CFSSL_URL}}
        dest={{CFSSL_DIR}}/cfssl_linux-amd64
        mode=0740

    - name: 下载{{CFSSLJSON_URL}}
      get_url:
        url={{CFSSLJSON_URL}}
        dest={{CFSSL_DIR}}/cfssljson_linux-amd64
        mode=0740
 
    - name: 下载{{CFSSLCERTINFO_URL}}
      get_url:
        url={{CFSSLCERTINFO_URL}}
        dest={{CFSSL_DIR}}/cfssl-certinfo_linux-amd64
        mode=0740
    
    - name: 下载解压ETCD {{ETCD_URL}}二进制安装包   
      unarchive:
        src={{ETCD_URL}}
        dest={{DATA_DIR}}
        remote_src=yes
 
    - name: 下载解压FLANNEL {{FLANNEL_URL}}二进制安装包   
      unarchive:
        src={{FLANNEL_URL}}
        dest={{FLANNEL_DIR}}
        remote_src=yes

    - name: 下载解压DOCKER {{DOCKER_URL}}二进制安装包
      unarchive:
        src={{DOCKER_URL}}
        dest={{DATA_DIR}}
        remote_src=yes

    - name: 下载解压KUBERNETES CLIENT {{KUBE_CLIENT_URL}}二进制安装包
      unarchive:
        src={{KUBE_CLIENT_URL}}
        dest={{DATA_DIR}}
        remote_src=yes

    - name: 下载解压KUBERNETES SERVER {{KUBE_SERVER_URL}}二进制安装包
      unarchive:
        src={{KUBE_SERVER_URL}}
        dest={{DATA_DIR}}
        remote_src=yes
    
