---
- hosts: all
  gather_facts: False
  remote_user: root
  become: yes
  become_method: sudo
  roles:
  - common

- hosts: etcd
  gather_facts: False
  remote_user: root
  become: yes
  become_method: sudo
  roles:
  - etcd

- hosts: flannel
  gather_facts: False
  remote_user: root
  become: yes
  become_method: sudo
  roles:
  - flannel

- hosts: kube-master
  gather_facts: False
  remote_user: root
  become: yes
  become_method: sudo
  roles:
  - master

- hosts: kube-node
  gather_facts: False
  remote_user: root
  become: yes
  become_method: sudo
  roles:
  - node





